### ISSUE TITLE
got weird texture png with sample-level decomposition code

### ISSUE THREAD

**Issue by yuminnko** [CyberAgentAILab/sprite-decompose#2]
Hi, thanks for the great work!

I tried to reproduce your result with given code and examples, but I got weird texture png results.
I used exactly same code from Sample-level Decomposition,
but i got texture png like this with iter 60000.

![1](https://github.com/user-attachments/assets/3bafea48-c28c-4997-a2ee-bb7755102d6b)
![2](https://github.com/user-attachments/assets/c0363e43-2887-46cf-9d0f-4660e271674c)
![3](https://github.com/user-attachments/assets/2be2afae-f177-4e39-acb4-46b76c23a714)
![4](https://github.com/user-attachments/assets/f0af9722-6297-4389-8d09-ad0bcddb85cc)
![0](https://github.com/user-attachments/assets/c02e23c1-bf3f-4211-95e2-c961c6453516)

**Comment by tomoyukun** [comment]
Thank you for your interest and for reporting this!
This is likely a bug in the texture saving. 
I’ll fix it, so please wait a little while.

**Comment by tomoyukun** [comment]
I've fixed this in https://github.com/CyberAgentAILab/sprite-decompose/pull/3.
